USE test_database;
CREATE OR REPLACE VIEW dwd_payin_orders_d AS
SELECT 
  busi_date,
  trade_no,
  out_trade_no,
  merchant_no,
  merchant_name,
  app_id,
  app_name,
  method,
  channel,
  order_currency,
  order_amount,
  pay_currency,
  pay_amount,
  settle_currency,
  settle_amount,
  channel_order_status,
  trade_status,
  create_time,
  update_time,
  user_unique_identification,
  region,
  order_duration,
  initial2progress_order_duraion,
  progress2final_order_duraion,
  initial2final_order_duraion
FROM ods_pagsmile_orders_raw;

CREATE OR REPLACE VIEW dwd_payout_orders_d AS
SELECT 
  busi_date,
  id,
  merchant_id,
  app_id,
  transaction_id,
  reference_id,
  beneficiary_id,
  username,
  phone,
  email,
  country,
  amount,
  payout_currency,
  arrival_amount,
  arrival_account,
  transaction_status,
  method,
  thirdparty_channel,
  user_unique_identification,
  arrival_unique_identification,
  create_time,
  update_time,
  initial_time,
  progress_time,
  final_time,
  order_final_duration,
  order_final_duration_exclude_weekend
FROM ods_transfersmile_payouts_raw;
